### ISSUE TITLE
"DataTables warning: You have an error in your SQL syntax"

### ISSUE THREAD

**Issue by christiangenco** [andris9/mailtrain#100]
Encountered when I click the magnifying glass next to the "Delivered" heading for a campaign in the middle of sending.

<img width="1280" alt="screen shot 2016-10-17 at 11 01 05 am" src="https://cloud.githubusercontent.com/assets/179361/19446659/6ccf8c1a-945f-11e6-882a-32248d73b8d9.png">

**Comment by andris9** [comment]
Did it start working once the campaign was sent or is this a permanent error?

**Comment by fredluhamaa** [comment]
It's permanent. I have exact same error.

**Comment by andris9** [comment]
Fixed by 8d2e5f23e646d79e7bfb3c20ca241c6268cb60a9
