### ISSUE TITLE
Feature Request - Support for Deployment through Docker

### ISSUE THREAD

**Issue by programster** [andris9/mailtrain#104]
It would be fantastic if this tool could be easily deployed through docker.  

From looking at the `install.sh` file, it appears this tool requires a redis server and a mysql/mariadb database. These could both be linked containers, or perhaps the connection/authentication details could be passed in as environment variables, which means that people could keep all "state" separately, such as on an RDS instance.

**Comment by gkostyanikov** [comment]
@programster https://github.com/andris9/mailtrain/pull/88

**Comment by andris9** [comment]
There's now a Docker image in master branch
