### ISSUE TITLE
Support specifying the reply-to field

### ISSUE THREAD

**Issue by nebulade** [andris9/mailtrain#108]
Hi there,

is it somehow possible to set the reply-to field for a campaign? I was unable to find any information about that. 

If it is not possible, is there a specific reason, this is not implemented? If not, I am happy to work on a change adding this feature.

Thanks

**Comment by andris9** [comment]
Curently it is not possible. The message is composed [here](https://github.com/andris9/mailtrain/blob/master/services/sender.js#L331-L378). To add Reply-To field, you shoud add a new field similar to "from" and name it "replyTo", something like this:

```javascript
from: {
    name: campaign.from,
    address: campaign.address
},
xMailer: 'Mailtrain Mailer (+https://mailtrain.org)',
replyTo: {
    name: 'Reply To Name',
    address: 'reply.to@address'
},
...
```
