### ISSUE TITLE
server process crash

### ISSUE THREAD

**Issue by controlcde** [andris9/mailtrain#11]
I use the test template to try mailtrain but every time I click the [LINK_BROWSER] link in the received email the server process will crash. I use a apache2 as proxy server in front of the mailtrain server. I got the error
```
/srv/mailtrain/node_modules/mysql/lib/protocol/Parser.js:77
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property 'hasOwnProperty' of undefined
    at key (/srv/mailtrain/lib/tools.js:161:35)
    at /srv/mailtrain/lib/tools.js:169:17
    at String.replace (native)
    at Object.formatMessage (/srv/mailtrain/lib/tools.js:167:20)
    at /srv/mailtrain/routes/archive.js:68:44
    at Query._callback (/srv/mailtrain/lib/models/campaigns.js:422:20)
    at Query.Sequence.end (/srv/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/srv/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/srv/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
    at Protocol._parsePacket (/srv/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:280:23)
```

**Comment by andris9** [comment]
Thanks! I updated the code to fix this issue. Currently there is no upgrade option, so you would have to re-upload mailtrain files to your server to get the fix. No need to modify the database or configuration files.

**Comment by nezam05** [comment]
Hi, I'm getting almost similar kind of erro
`0 info it worked if it ends with ok
1 verbose cli [ '/home/nezam/.nvm/versions/node/v7.2.1/bin/node',
1 verbose cli   '/home/nezam/.nvm/versions/node/v7.2.1/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--production' ]
2 info using npm@4.0.5
3 info using node@v7.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mailtrain@1.20.0~prestart: mailtrain@1.20.0
6 silly lifecycle mailtrain@1.20.0~prestart: no script for prestart, continuing
7 info lifecycle mailtrain@1.20.0~start: mailtrain@1.20.0
8 verbose lifecycle mailtrain@1.20.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle mailtrain@1.20.0~start: PATH: /home/nezam/.nvm/versions/node/v7.2.1/lib/node_modules/npm/bin/node-gyp-bin:/home/nezam/mailtrain/node_modules/.bin:/home/nezam/.nvm/versions/node/v7.2.1/bin:/home/nezam/.rbenv/shims:/home/nezam/.rbenv/bin:/home/nezam/nodejs/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle mailtrain@1.20.0~start: CWD: /home/nezam/mailtrain
11 silly lifecycle mailtrain@1.20.0~start: Args: [ '-c', 'node index.js' ]
12 silly lifecycle mailtrain@1.20.0~start: Returned: code: 1  signal: null
13 info lifecycle mailtrain@1.20.0~start: Failed to exec start script
14 verbose stack Error: mailtrain@1.20.0 start: `node index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/nezam/.nvm/versions/node/v7.2.1/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/nezam/.nvm/versions/node/v7.2.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid mailtrain@1.20.0
16 verbose cwd /home/nezam/mailtrain
17 error Linux 3.16.0-4-amd64
18 error argv "/home/nezam/.nvm/versions/node/v7.2.1/bin/node" "/home/nezam/.nvm/versions/node/v7.2.1/bin/npm" "start" "--production"
19 error node v7.2.1
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error mailtrain@1.20.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the mailtrain@1.20.0 start script 'node index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the mailtrain package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs mailtrain
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls mailtrain
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]`

As i am newbie to node world, can you please guide me to fix this problem? TIA.
