### ISSUE TITLE
Feature request: Optionally upload images to external host

### ISSUE THREAD

**Issue by davidbrenner** [andris9/mailtrain#113]
I naively uploaded a bunch of images to a template without thinking (or realizing) that they are encoded and embedded in the email itself. These images were rather large and were ultimately too large to be sent via email.

I read through Mail Chimp's recommendations on images: https://templates.mailchimp.com/design/images/

I'd like to request an option to upload images to an external image host through the mailtrain visual editor. I realize this is a potentially massive feature request as there are tons of ways this could be implemented and likely none of them will match the exact infrastructure each user is looking for. I am willing to help with this where I can. I just want to start the discussion.

For me, I'd like uploaded images to be dumped into an s3 bucket and then serve them via cloudfront.

**Comment by andris9** [comment]
On the usability side it would be a huge improvement and I've also considered it but I have basically dropped all work on the editor side as the current editor is not very suitable for emails. The editor needs to be replaced by something else sooner or later and thus i do not want to invest any time into the current one.

**Comment by davidbrenner** [comment]
Thanks for replying so quickly.

In that case, maybe a good start would be to look into integrating with an already established editor? https://github.com/voidlabs/mosaico looks pretty good, though I haven't actually used it.

**Comment by andris9** [comment]
Yeah, Mosaico has been discussed before and it's a solid choice. It's not something too easy to integrate though, it's not like with regular wysiwyg editors where you just include a javascript file, set a specific class name to a textarea element and your done. Mosaico is more like an application on its own, I'm not sure if it is even possible to embed it inside another webpage or you need to open a separate window for it.

**Comment by davidbrenner** [comment]
Agreed. I poked around at the codebase. I think for my current infrastructure, I would just launch mosaico as its own application and then modify mailtrain to launch a new window opening mosaico when I click to edit a template. Then just grab the html from mosaico and shove it into the mailtrain template.

Mosaico still has issues with storing images too. So they're only a couple steps ahead of mailtrain's current editor in terms of that level of customization.

Maybe the best path forward for mailtrain is to just include the current editor and add a simple interface for slightly more "integrated" support of external editors?

**Comment by andris9** [comment]
Mailtrain now natively supports Mosaico, it is built in
