### ISSUE TITLE
Authentication failed zone-mta

### ISSUE THREAD

**Issue by santimacia** [andris9/mailtrain#119]
Hi, I'm trying to setup mailtrain with Amazon SES.
I have the domain verified with Amazon, and the smtp configuration says verification ok..
The server ports 80,22,443 and 25 are open. What else should check?

`(Plugins) Error: Authentication failed#012    at PassThrough.req.once.err (/opt/zone-mta/plugins/core/http-auth.js:29:27)#012    at PassThrough.g (events.js:291:16)#012    at emitOne (events.js:96:13)#012    at PassThrough.emit (events.js:188:7)#012    at ClientRequest.req.on.res (/opt/zone-mta/node_modules/nodemailer-fetch/lib/fetch.js:179:22)#012    at emitOne (events.js:96:13)#012    at ClientRequest.emit (events.js:188:7)#012    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)#012    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)#012    at Socket.socketOnData (_http_client.js:363:20)#012 "%s" for "%s" failed with: %s HTTP Basic Authorization smtp:auth Error: Authentication failed#012    at PassThrough.req.once.err (/opt/zone-mta/plugins/core/http-auth.js:29:27)#012    at PassThrough.g (events.js:291:16)#012    at emitOne (events.js:96:13)#012    at PassThrough.emit (events.js:188:7)#012    at ClientRequest.req.on.res (/opt/zone-mta/node_modules/nodemailer-fetch/lib/fetch.js:179:22)#012    at emitOne (events.js:96:13)#012    at ClientRequest.emit (events.js:188:7)#012    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)#012    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)#012    at Socket.socketOnData (_http_client.js:363:20)`

**Comment by andris9** [comment]
If you can't get authentication working then you can disable authentication in ZoneMTA by setting `smtpInterfaces->feeder->authentication: false` in */opt/zone-mta/config/production.json*, in Mailtrain config mark the checkbox "Disable SMTP authentication"

**Comment by santimacia** [comment]
Now its worse

`ERR! Mail Error: Invalid login: 500 Error: command not recognized
Dec 23 16:33:41 ip-172-30-0-123 node[22072]: ERR! Mail     at SMTPConnection._formatError (/opt/mailtrain/node_modules/smtp-connection/lib/smtp-connection.js:528:15)
Dec 23 16:33:41 ip-172-30-0-123 node[22072]: ERR! Mail     at SMTPConnection._actionAUTHComplete (/opt/mailtrain/node_modules/smtp-connection/lib/smtp-connection.js:1231:30)
Dec 23 16:33:41 ip-172-30-0-123 node[22072]: ERR! Mail     at SMTPConnection.<anonymous> (/opt/mailtrain/node_modules/smtp-connection/lib/smtp-connection.js:319:22)
Dec 23 16:33:41 ip-172-30-0-123 node[22072]: ERR! Mail     at SMTPConnection._processResponse (/opt/mailtrain/node_modules/smtp-connection/lib/smtp-connection.js:669:16)
Dec 23 16:33:41 ip-172-30-0-123 node[22072]: ERR! Mail     at SMTPConnection._onData (/opt/mailtrain/node_modules/smtp-connection/lib/smtp-connection.js:493:10)
Dec 23 16:33:41 ip-172-30-0-123 node[22072]: ERR! Mail     at emitOne (events.js:96:13)
Dec 23 16:33:41 ip-172-30-0-123 node[22072]: ERR! Mail     at Socket.emit (events.js:188:7)
Dec 23 16:33:41 ip-172-30-0-123 node[22072]: ERR! Mail     at readableAddChunk (_stream_readable.js:176:18)
Dec 23 16:33:41 ip-172-30-0-123 node[22072]: ERR! Mail     at Socket.Readable.push (_stream_readable.js:134:10)
Dec 23 16:33:41 ip-172-30-0-123 node[22072]: ERR! Mail     at TCP.onread (net.js:548:20)`

**Comment by andris9** [comment]
After you modify zone-mta config restart the service by calling

    sudo service zone-mta restart

**Comment by andris9** [comment]
Are you sure that you marked the checkbox "Disable SMTP authentication" in Mailtrain? It seems that you are still trying to log in to ZoneMTA

**Comment by santimacia** [comment]
"Disable SMTP authentication" and clicked on update settings

**Comment by andris9** [comment]
This should be now fixed in the master branch. When you updated connection options then these changes were not propagated to sending processes
