### ISSUE TITLE
External SMTP already setup but Keeps sending using Local MTA

### ISSUE THREAD

**Issue by rhbkweb** [andris9/mailtrain#120]
Hi,

First let me say, that MailTrain seems great! Good work!

I made today for the first time a clean install on a VPS KVM UBUNTU 16.04 and after install, I made just one test using the Local MTA to see if all was ok. The email was sent ok.

Then I changed the SMTP settings at Admin > Settings > to use my SparkPost SMTP account and clicked on "Check SMTP Config" and the test gives ok. I then clicked on Save on the page bottom. 

But when I then go send a new campaign, it keeps sending the emails using the Local MTA instead of the External SMTP (SparkPost). I have checked the headers and the emails comes directly from my server instead of using SparkPost.

If I logout and login again, and go to settings I can see there the SparkPost SMTP settings are saved, as you can see on the image screenshot that i have taken: http://imgur.com/a/QTUml

So how/why does Mailtrain does not send the emails using SparkPost?

Can you please tell me if I'm doing something wrong or if this is a bug/problem with MailTrain?

If from my end you need any further information, just ask me.

Thanks

**Comment by andris9** [comment]
This should be now fixed in the master branch. When you updated connection options then these changes were not propagated to sending processes
