### ISSUE TITLE
SSL Certificate Installation

### ISSUE THREAD

**Issue by rhbkweb** [andris9/mailtrain#121]
Hi,

Is it possible to install/use an SSL Certificate with MailTrain to betetr secure the installation? 

If yes, is there any guide on how to install SSL certificate? If not, can you please just give a simple explanation of the what is needed to make a SSL Certificate to work with Mailtrain?

Thanks

**Comment by andris9** [comment]
It usually makes more sense to do the SSL termination in some kind of proxy server, eg. in Nginx or Apache, this way you can also set up redirects for http to https etc. An example virtual domain configuration for Nginx would look like this:

```nginx
# HTTP server for example.com to redirect to HTTPS
server {
    listen 80;
    listen [::]:80;

    server_name example.com;
    return 301 https://example.com$request_uri;
}

# HTTP server for example.com that proxies requests to Mailtrain running on port 3000
server {
    listen 443;
    listen [::]:80;
    ssl on;
    ssl_certificate /path/to/cert.pem;
    ssl_certificate_key /path/to/key.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    server_name example.com;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header HOST $http_host;
        proxy_set_header X-NginX-Proxy true;

        proxy_pass http://127.0.0.1:3000;
        proxy_redirect off;
    }
}
```
