### ISSUE TITLE
Send campaign emails in plain-text only

### ISSUE THREAD

**Issue by botherder** [andris9/mailtrain#128]
For security reason, we would like to be able to send campaign emails only in plain text, with no HTML part. Particularly given that it seems that Mailtrain does embed some sort of hidden resource for tracking reads by default, and I haven't been able to find an option to disable it.

Do you think that would be useful/possible?

**Comment by andris9** [comment]
There was a bug in Mailtrain that prevented skipping HTML. The current master allows that.

1. To use plaintext messages, go to settings and mark the checkbox "Disable WYSIWYG editor". Then open campaign settings and delete everything in the HTML textbox. Use the plaintext textbox for your message
2. To disable tracking, then mark the checkbox "Disable clicked/opened tracking" when creating a new campaign or edit an existing one. This mostly applies only if you use HTML content as plaintext content does not contain any tracking data anyway. If you have already sent out a HTML campaign with tracking data and you mark this checkbox then user interaction is not stored (the server does get redirect requests etc and these requests might get logged in server access log but user data is not updated in the database)
