### ISSUE TITLE
Import into custom fields from CSV file?

### ISSUE THREAD

**Issue by gregshep** [andris9/mailtrain#129]
I've tried and cannot seem to import into custom fields.  I don't get any errors that I can find but no lines are imported.  Thanks for any suggestions.

**Comment by andris9** [comment]
I created a Wiki page [here](https://github.com/andris9/mailtrain/wiki/Import-from-CSV) for it as it might be relevant for other users as well.

If your import does not work at all, then maybe an error is thrown which halts the import. Could you check from your server logs if there are any errors after you start the import?

**Comment by gregshep** [comment]
I recreated my AWS instance and followed your Wiki page details.  It works!  Thank you for the prompt help and I realize I must have done something wrong.  BTW, there were no errors or messages in /var/log/syslog (Ubuntu).
Thanks for the Wiki page!
