### ISSUE TITLE
Unsubscribe link redirect

### ISSUE THREAD

**Issue by mattmoesen** [andris9/mailtrain#136]
Hello,

i have a question: ist it possible to add a redirect param to the unsubscribe-link?
This would be really great, so that one can make a custom success or error page after the unsubscribe process. So even two params might be better, for example [LINK_UNSUBSCRIBE]?suc-url=[SUCCESS_URL]&err-url=[ERROR_URL]

Is something like this is possible at the moment, or is this planned for future development?

br,
Matthias

**Comment by andris9** [comment]
Redirects are not possible. I think that the best way to handle this would be to use the Mailtrain API. Instead of the built in unsubscribe_url use your own url and the targeted script could call the actual unsubscribe action through API and then show some custom output.

**Comment by mattmoesen** [comment]
ok, thank you for the information. 
already tried this approach. works fine for us, only in the statistics the unsubscribe value won't be correct.
