### ISSUE TITLE
How to add new users to a list through an API

### ISSUE THREAD

**Issue by rnarayan** [andris9/mailtrain#140]
I have a website where around 80-100 users sign-up every day. Currently, I use mailgun to confirm their email. 

I would like to send new users one email every day for the next 5 days introducing different features of the website. I think I can achieve this using the automation feature in MailTrain.

My question is - can I add these users to MailTrain through an API? App and Mail Train will run on different servers. Creating 80-100 users every day manually is not feasible.

**Comment by andris9** [comment]
Yes, you can add users through the API. You can see the API documentation and examples once you have set up Mailtrain and logged in.
