### ISSUE TITLE
New subscribers aren't always given the next highest #

### ISSUE THREAD

**Issue by bensulli** [andris9/mailtrain#146]
When I add new subscribers they don't seem to always get the next highest "#" field. So sorting by # doesn't always give me a chronological list of subscribers to a certain list. Looking around the database I don't see a "#" field anywhere, so I'm guessing this is just a number applied to a list in the php but why isn't it sorted by created ascending then?

Another solution would be to simply always show the 'created' field when you're viewing a list of subscribers and let you sort by it. Or just have the "#" always be the id of the user from the table.

Update: Noticed that the list is always sorted by e-mail alphabetically by default, and the # is simply the row number. Ideally there'd always be a generated column for 'Added Date' based on created in the table, and that could be sorted on.

**Comment by andris9** [comment]
The # is just a sorting order number. The list by default is sorted by email address in alphabetical order. I understand why you would want to order subscribers by added date, so I added the "created" field to the subscribers list table that can be used for ordering bd6ba90ecadc934a1eef5ba497d57a57a44112b3

**Comment by bensulli** [comment]
Very awesome, much appreciated!

**Comment by bensulli** [comment]
FYI, works perfectly! Thanks!
