### ISSUE TITLE
Spaces added to plaintext template

### ISSUE THREAD

**Issue by DecentM** [andris9/mailtrain#148]
Whenever I save a template, four spaces get added to the beginning of all lines but the first, both if there were none before or if they already existed. The first screenshot is of the default template, the second one is of its state after clicking the update button without any other modifications.  
![screenshot_20170304_233745](https://cloud.githubusercontent.com/assets/4973610/23582812/958edb74-0133-11e7-8d4a-e8ea6e47f1be.png)  
![screenshot_20170304_233817](https://cloud.githubusercontent.com/assets/4973610/23582814/a6478498-0133-11e7-82fe-803ae29174ed.png)

**Comment by andris9** [comment]
Fixed
