### ISSUE TITLE
can not access mydomain

### ISSUE THREAD

**Issue by sun-yunrui** [andris9/mailtrain#151]
hello,
  i created a new VPS to install mailtrain, i run `curl https://raw.githubusercontent.com/andris9/mailtrain/master/setup/install.sh | sudo bash
` after upgrade software, and installed successfully. i created a new domain for this server, but i can not access. and no process is using port 80.

sunyr@mailtrain-03-06-2017:~$ sudo netstat -lnpa | grep ':80'
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      6472/zone-mta: mast
tcp        0      0 127.0.0.1:8081          0.0.0.0:*               LISTEN      6472/zone-mta: mast
tcp        0      0 127.0.0.1:59738         127.0.0.1:8081          ESTABLISHED 6496/default
tcp        0      0 127.0.0.1:59702         127.0.0.1:8081          TIME_WAIT   -
tcp        0      0 127.0.0.1:59746         127.0.0.1:8081          ESTABLISHED 6497/bounces
tcp        0      0 127.0.0.1:8081          127.0.0.1:59750         ESTABLISHED 6472/zone-mta: mast
tcp        0      0 127.0.0.1:59742         127.0.0.1:8081          ESTABLISHED 6521/default
tcp        0      0 127.0.0.1:59710         127.0.0.1:8081          TIME_WAIT   -
tcp        0      0 127.0.0.1:59706         127.0.0.1:8081          TIME_WAIT   -
tcp        0      0 127.0.0.1:59744         127.0.0.1:8081          ESTABLISHED 6509/feeder
tcp        0      0 127.0.0.1:59712         127.0.0.1:8081          TIME_WAIT   -
tcp        0      0 127.0.0.1:59748         127.0.0.1:8081          ESTABLISHED 6503/transactional
tcp        0      0 127.0.0.1:59708         127.0.0.1:8081          TIME_WAIT   -
tcp        0      0 127.0.0.1:8081          127.0.0.1:59742         ESTABLISHED 6472/zone-mta: mast
tcp        0      0 127.0.0.1:8081          127.0.0.1:59738         ESTABLISHED 6472/zone-mta: mast
tcp        0      0 127.0.0.1:59704         127.0.0.1:8081          TIME_WAIT   -
tcp        0      0 127.0.0.1:59714         127.0.0.1:8081          TIME_WAIT   -
tcp        0      0 127.0.0.1:8081          127.0.0.1:59748         ESTABLISHED 6472/zone-mta: mast
tcp        0      0 127.0.0.1:59740         127.0.0.1:8081          ESTABLISHED 6490/feeder
tcp        0      0 127.0.0.1:8081          127.0.0.1:59746         ESTABLISHED 6472/zone-mta: mast
tcp        0      0 127.0.0.1:59750         127.0.0.1:8081          ESTABLISHED 6522/default
tcp        0      0 127.0.0.1:59724         127.0.0.1:8081          TIME_WAIT   -
tcp        0      0 127.0.0.1:8081          127.0.0.1:59744         ESTABLISHED 6472/zone-mta: mast
tcp        0      0 127.0.0.1:8081          127.0.0.1:59740         ESTABLISHED 6472/zone-mta: mast

anybody can help me? 
Thanks a lot.

**Comment by sun-yunrui** [comment]
Oh! found why.
in https://github.com/andris9/mailtrain/blob/master/setup/install.sh line:93 `npm install --no-progress --production`,  the package `gettext-parser` is not be installed.

**Comment by andris9** [comment]
Oh, yeah, I thought that I already fixed it. Apparently not. The gettext-parser is not a development but production dependency. Fixed with the latest commit
