### ISSUE TITLE
Error on import failed page

### ISSUE THREAD

**Issue by heroic** [andris9/mailtrain#154]
For some reason I keep getting this error:

Parse error on line 49: ... </table></div> ---------------------^ Expecting 'OPEN_INVERSE_CHAIN', 'INVERSE', 'OPEN_ENDBLOCK', got 'EOF'

On the import failed page: /lists/subscription/2/import/17/failed

I did a quick check of the template, but dont see any issue anywhere!

**Comment by andris9** [comment]
Checked the file and there's unmatching translate tag after the long "Role-based addresse..." string. I'll fix it once I'm at my computer, can't do it with mobile
