### ISSUE TITLE
SES: Doesn't seem to be handling bounces/complaints

### ISSUE THREAD

**Issue by heroic** [andris9/mailtrain#159]
I just sent a test campaign to some 700 subscribers, and got some 10 bounces, but there are no bounces reported in mailtrain. I also got 3 complaints, but nothing in mailtrain again.

I have setup the SNS topics and subscriptions to the url domain.com/webhooks/aws. The subscriptions are also confirmed.

**Comment by raman3366** [comment]
Is it "https://domain.com/webhooks/aws". make sure it is https. http authentication caused problem for me too. Switched to https, now works great.
