### ISSUE TITLE
SES SNS notifications are not working

### ISSUE THREAD

**Issue by heroic** [andris9/mailtrain#160]
Ok, so I have debugged this to a great extent. It seems that the notification is delivered to the webhook, but the webhook is unable to find the response in the DB. When I check manually the response is comfortably present in the db. Now I can only assume that this could have something to do with the sender now saving the response in time. But it's not a really easy a task to find out!

Any help is appreciated!

**Comment by andris9** [comment]
This should be fixed by upgrading Nodemailer. 6ef9836c144c9ea2b0b6af7016f892dc0d1d9be7
