### ISSUE TITLE
How does a user sign up?

### ISSUE THREAD

**Issue by vanthome** [andris9/mailtrain#177]
Hi, after reading the wiki and on the homepage, it is unclear to me, how mail recipients are signing up to the service? Is there a REST API for that or is this out of scope?
BG

**Comment by andris9** [comment]
In general the flow is the following:

1. You download and install Mailtrain in your server
2. You log in as admin and create a subscription list
3. In the subscription list view there's a button "Subscription form" this opens a window with the subscription form. This is also the link your subscribers should got to.

**Comment by vanthome** [comment]
many thanks for the response!
But what if I have a single page application where I want to build the form with my own HTML/ CSS/ Templates and stuff. Then a REST API would be nice that I could use, isn't it?

**Comment by andris9** [comment]
Mailtrain has built in API. Once you have set it up, log in and you should find API link to documentation and API key from the user menu

**Comment by witzig** [comment]
http://mailtrain.org/images/screenshots/users/api.png

**Comment by vanthome** [comment]
oh, great! that's exactly what I was looking for!
Actually this is mentioned here: https://github.com/andris9/mailtrain/wiki/Using-API

**Comment by vanthome** [comment]
ok, that works great, there is only one issue I have with it:
I cannot use the API directly from a single page application as I cannot limit the scope of the access token to only subscription. That would be a nice feature... please correct me if I'm wrong.

**Comment by andris9** [comment]
Yes, you need a server component for it. Probably something simple that takes the subscription details from your front-page app and makes an API call to subscribe the user.

**Comment by nitin347** [comment]
> In general the flow is the following:
> 
> 1. You download and install Mailtrain in your server
> 2. You log in as admin and create a subscription list
> 3. In the subscription list view there's a button "Subscription form" this opens a window with the subscription form. This is also the link your subscribers should got to.

can u please send the configuration steps to install in my server

**Comment by stoplion** [comment]
I'm confused too, where is the sign up form?
