### ISSUE TITLE
MYSQL error - improve error message

### ISSUE THREAD

**Issue by lightonflux** [andris9/mailtrain#18]
When you forgot to configure your mysql password or user the webUI exposes the plain MYSQL error message:

> Err: 'Access denied for user: 'mailtrain@localhost' (Using password: YES)' 

People inexperienced with MySQL might not know that is a an error with the database connection. The web interface should at least mention that this is an error coming back from mysql.

Something like that:

> MySQL Error: 'Access denied for user: 'mailtrain@localhost' (Using password: YES)'

A message with more information would be more user friendly, like this:

> Your MySQL username or password appears to be wrong. Check config/production.toml for the right values!

Or something.

**Comment by andris9** [comment]
The latest version tries to connect to the database even before starting listening on the www port you do not get these errors anymore. If MySQL connection fails then server would not start.

I updated the error messages logged to console so now you should see error messages like "Could not access the database. Check MySQL config and authentication credentials" or "Could not connect to the database. Check MySQL host and port configuration".
