### ISSUE TITLE
Show email addresses that failed processing after list subscriber import

### ISSUE THREAD

**Issue by SathyaBhat** [andris9/mailtrain#21]
When subscriber list is imported, at times some emails fail to be imported for valid reasons(domain no longer valid, MX not found etc). It would be nice if these errors are logged and stored in a table somewhere so that post import, we can go and see what the errors were.

Currently these errors are logged but not shown anywhere

**Comment by andris9** [comment]
Great idea. This would be fairly easy to add as well, the only thing stopping me right now is that i have to figure out a database update procedure first as this feature would require some additions to the existing db structure. So far I have avoided changes to the db structure but sooner or later this needs to be addressed.

**Comment by andris9** [comment]
Fixed in v1.2.0. To upgrade simple copy new files over old ones or alternatively, if you have downloaded the files using `git clone` then run `git pull origin master` to get the updated files.
