### ISSUE TITLE
[Enhancement] Plain HTML editor

### ISSUE THREAD

**Issue by radleta** [andris9/mailtrain#22]
We are having problems with the current template HTML editor stripping important markup from the HTML. It would be nice to have an option to just provide the raw HTML and turn off the HTML editor to prevent it sanitizing the HTML of the template.

PS - Nice work on the project. Easy setup and very useful.

**Comment by andris9** [comment]
The latest version has a configuration option to disable WYSIWYG editor. I'll add the button next to the editor itself as well but currently you can disable it through Settings page

**Comment by radleta** [comment]
Thanks for the quick response. I'll update and use that setting to resolve the issue.
