### ISSUE TITLE
[Enhancement] Simple scheduling of send start time

### ISSUE THREAD

**Issue by radleta** [andris9/mailtrain#23]
We'd love to see an option to set the start time of the send of the campaign. Nothing fancy needed just a start time for the system to start sending would be enough to solve lots of our issues.

**Comment by andris9** [comment]
Good idea

**Comment by JensC** [comment]
+1 for that.

**Comment by andris9** [comment]
Scheduling is now available from the v1.3 development branch, see usage instructions [here](https://github.com/andris9/mailtrain/wiki/Scheduling-Send-time).

**Comment by tuck1s** [comment]
This is nice.
The UI currently allows selection of "negative" time offset which is probably a bug, unless we have a time-machine ;-)
A calendar based UI allowing choice of actual dates/times would be even nicer (that's how paid systems like Ongage do it), that would require timezone awareness, which gets _interesting_ around daylight saving changes.
![screenshot 2017-06-22 22 04 26](https://user-images.githubusercontent.com/11942927/27455917-e39ce2ca-5796-11e7-8315-0ce855adb714.png)
