### ISSUE TITLE
Merge tags doesn't work with links

### ISSUE THREAD

**Issue by sageeki** [andris9/mailtrain#24]
We absolutely love MailTrain and looking forward seeing it growing. 
There's one issue we noticed so far, whenever you use a merge tag (for example: [FIRST_NAME]) with a link: http://whatever.io/invite?[FIRST_NAME] the merge tag fail to translate into the actual first name.

Any quick fixes? :)
Thanks,
-S.

**Comment by andris9** [comment]
Fixed in v1.2.0. To upgrade simple copy new files over old ones or alternatively, if you have downloaded the files using `git clone` then run `git pull origin master` to get the updated files.

**Comment by sageeki** [comment]
Sweet. Thanks!
