### ISSUE TITLE
How to edit Bounce settings?

### ISSUE THREAD

**Issue by SudoHenk** [andris9/mailtrain#25]
I use my own mailserver on localhost and route every outgoing mail to mailgun (but incoming dicrectly). On the homepage you state that you can set the webhook for these mail providers, but where or how can I set these parameters?

**Comment by andris9** [comment]
I created a wiki page about setting up Webhooks for Mailgun: https://github.com/andris9/mailtrain/wiki/Setting-up-Webhooks-for-Mailgun
