### ISSUE TITLE
[Load Balanced] Is mailtrain architected to be used in a web farm?

### ISSUE THREAD

**Issue by radleta** [andris9/mailtrain#29]
I'd like to be able to have more than one instance of mailtrain running to ensure uptime. Is the application designed to be able to play well when multiple instances are connected to the same database?

PS - Keep up the good work.

**Comment by andris9** [comment]
Yes, Mailtrain is supposed to be multi-process/multi-host friendly. If it doesn't work this way then there's a bug somewhere. Each process adds additional load against the MySQL server but this should normally not be an issue.
