### ISSUE TITLE
Node server not getting started

### ISSUE THREAD

**Issue by kunwarakash** [andris9/mailtrain#3]
I am getting following error. My node version is v0.10.41 and npm is 3.8.5.

/home/akash/experimental/mailtrain/mailtrain-master/index.js:6
let config = require('config');
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

npm ERR! Linux 3.16.0-44-generic
npm ERR! argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.10.41
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! mailtrain@1.0.0 start: `node index.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the mailtrain@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mailtrain package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mailtrain
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mailtrain
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/akash/experimental/mailtrain/mailtrain-master/npm-debug.log

**Comment by andris9** [comment]
Mailtrain requires Nodejs v5+ (see the [requiremenets](https://github.com/andris9/mailtrain#requirements)]. Node v0.10 is not supported.
