### ISSUE TITLE
UNINSTALL

### ISSUE THREAD

**Issue by andreaolivieri87** [andris9/mailtrain#32]
Please can you tell somewhere how to completely uninstall mailtrain from Ubuntu (14.04)?

I installed it with the "### Automatic install (Ubuntu 14.04)" method, then i tried to access to "http://localhost:3000/", but receiving "ERR_CONNECTION_REFUSED" from the browser.

Probably i missed to do something, if you can help me i'm very happy, thx :). 
In any case i would like to be able to clean my os.

Thank you for the support and thank you VERY MUCH for the community work.

**Comment by andris9** [comment]
If you used install script then it set up the server on port 80, not 3000 so you should try to open [http://localhost](http://localhost/)

To uninstall, stop the service first

    service mailtrain stop

and then remove all relevant files

    rm -rf /opt/mailtrain
    rm /etc/init/mailtrain.conf 
    rm /etc/logrotate.d/mailtrain
    rm /var/log/mailtrain.log

Mailtrain installation also adds some additional packages but to rempve these you should be sure that these are not used by anything else

  * mysql-server
  * pwgen
  * redis-server
  * nodejs
  * git
  * ufw
