### ISSUE TITLE
DB Upgrade Instructions

### ISSUE THREAD

**Issue by radleta** [andris9/mailtrain#35]
I noticed you revamped the SQL scripts to allow for incremental upgrades. I didn't see anything mentioning how to upgrade the existing SQL DB. I'm assuming I'd just run the setup/sql/upgrade-#####.sql in order on the DB?

Please provide guidance.

**Comment by andris9** [comment]
There are no instructions, just run the app – before doing anything else the app checks currently existing db schema and if it is out of date then applies any pending updates.

**Comment by radleta** [comment]
Excellent! Thanks.
