### ISSUE TITLE
Custom API Integration

### ISSUE THREAD

**Issue by radleta** [andris9/mailtrain#36]
We have a custom sign up form for our newsletter. We need to be able to add users to subscription lists. I can see two different ways to do it either via SQL or Web API on the front-end. What is your recommendation?

I should also mention we don't want to send the email that says click here to begin subscription. It would be a silent subscribe.

**Comment by andris9** [comment]
I have planned a simple API for these kind of signups, I expect to get a first version up in the next few days.

**Comment by radleta** [comment]
Excellent! Looking forward to seeing it.

**Comment by andris9** [comment]
First version of the API is now available (Mailtrain v1.6.0). See the usage instructions [here](https://github.com/andris9/mailtrain/wiki/Using-API)

**Comment by radleta** [comment]
Thanks. I'll try it out.
