### ISSUE TITLE
Connect to MAMP MySQL?

### ISSUE THREAD

**Issue by githubber** [andris9/mailtrain#40]
Looks interesting. I'm curious about comparing it to Sendy. I'm trying to run it on my Mac but it won't connect to the MySQL which MAMP runs. Any suggestions?
Thank you!

**Comment by tnViking** [comment]
@githubber What is the MySQL user you're trying to connect with?

**Comment by moussaclarke** [comment]
@githubber have you added the port number into the mySQL config? usually 8889 on MAMP out of the box but you can check it in phpmyadmin. I'm running MAMP and process was as follows, after app downloaded and production.toml copied as per  the readme.

1. Set up a 'mailtrain' database and user with relevant privileges in phpmyadmin.
2. Make sure db, user and password details from step 1 correct in the production.toml config file in the [mysql] section. host should be "localhost"
3. Add the line
`port=8889`
in that same [mysql] part
4. Change [www] host to "127.0.0.1"
4. Start up the app from terminal as per readme and go to localhost:3000

Hope that helps!

**Comment by andris9** [comment]
I'll add a default port option to the default config file, so it would be easier to switch ports if needed.

**Comment by githubber** [comment]
Hi, thanks for the responses, sorry I was traveling at the time. 
@moussaclarke the tweaks did not work, still fails. There are actually two sets of fail messages, one in the log, and on in the terminal. I really would like to try this out so forgive me for posting more, it would bre great to get to the bottom of this. Off the top of my head I recall apps needing to include a symlink or something to the mysql socks port for MAMP MySQl to be accessible from apps outside of the MAMP environment. But when I tried adding this sort of detail the config file failed to be parsed with an error that it was not expecting characters such as '/'.

Here is the error message from the terminal:
`me:mailtrain me$ NODE_ENV=production npm start

> mailtrain@1.6.0 start /Users/me/mailtrain
> node index.js

Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
ERR! DB Could not connect to the database. Check MySQL host and port configuration

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.9.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! mailtrain@1.6.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mailtrain@1.6.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mailtrain package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mailtrain
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mailtrain
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/me/mailtrain/npm-debug.log`


and here it is from the log file:

[npm-debug copy.txt](https://github.com/andris9/mailtrain/files/264329/npm-debug.copy.txt)

**Comment by githubber** [comment]
Hi again,
After looking around more I came across a [site](http://stackoverflow.com/questions/13085663/nodejs-on-mac-error-when-connecting-to-mysql) that suggested turning off local access within MAMPs control panel . So I did so and then mailtrain started up wonderfully. Thank you for your help, and apologies for the rabbit trail.
