### ISSUE TITLE
Multilingual mail support

### ISSUE THREAD

**Issue by carnevlu** [andris9/mailtrain#41]
hi,

for the moment I never see a provider that allow the send of a mail with multiple version, one for each languages.

It'll possible to add the features?

This kind of feature will require some supplementary information in the campaign:
- 1 default language (or template ref) for each campaign 
- the [MERGE_TAG] that indicate the language for each user
- the attribute language for a template, or multiple content for a template, one for languages

What do you think?

**Comment by andris9** [comment]
I don't think I would add some special interface for multilingual messages but it would probably be solved by #39
