### ISSUE TITLE
API Subscribe with verification email

### ISSUE THREAD

**Issue by tnViking** [andris9/mailtrain#43]
I've played with the API, and I see that the users don't get a verification email when they're added through the API. Would it be possible to do this?

**Comment by andris9** [comment]
I created a new tag v1.7.0 of Mailtrain that has an addtional option "REQUIRE_CONFIRMATION" for subscriptions. If you set this value to "yes" then a verification message is sent to the user.

Example:

```
curl -XPOST http://example.com/api/subscribe/B16uVTdW?access_token=abcdef\
     --data 'EMAIL=test@example.com&REQUIRE_CONFIRMATION=yes'
```

**Comment by tnViking** [comment]
Perfect, thank you 😄
