### ISSUE TITLE
Required MySQL privileges?

### ISSUE THREAD

**Issue by tnViking** [andris9/mailtrain#44]
What is the privileges mailtrain need? I don't want to grant it all privileges in case in a hack, and loose all data in the database

**Comment by andris9** [comment]
In addition to normal table operations, Mailtrain creates tables, alters tables, creates indexes, locks rows and maybe something else, the complete privileges set is not yet fixed - for example Mailtrain does not use triggers or views now but might in the future. Mailtrain user does not need any global level privileges (CREATE USER, FILE etc).

I would suggest not re-using databases but giving each application its own dedicated db and user.
