### ISSUE TITLE
Feature : See who opened the email

### ISSUE THREAD

**Issue by preexo** [andris9/mailtrain#45]
Mailtrain has evolved so fast so awesome! We are planning to start using it in production now, but it would be good to see who opened the sent out emails, including the time of opening.
Any plans to put this on the roadmap?

**Comment by andris9** [comment]
I've been busy lately get my [funding campaign](https://igg.me/at/mailtrain/8720095) going but I have also created this feature, it has been available from the v1.8 branch, I just pushed it to master. If you'd update your code then you should see an arrow link next to the click count of a link and if you follow that link you should end up with a list of subscribers who have clicked on this.

**Comment by andris9** [comment]
Did not understand the request, the update lists clicks not opens. I'll add the opens info as well

**Comment by andris9** [comment]
Added missing views, tagged as v1.8.3

**Comment by preexo** [comment]
+1 Wow you are so quick with implementations, thanks a lot, great feature!
