### ISSUE TITLE
Segment Rule Issue: Date Range with blank End Date doesn't filter as expected

### ISSUE THREAD

**Issue by radleta** [andris9/mailtrain#48]
It would appear you can create a Rule for a Segment of a List with a Date Range that has a Start Date and leave the End Date blank. This would be something similar to Start Date: 5/1/2016 and End Date: n/a returning all subscribers equal to or after 5/1/2016. The actual result is nothing is found.

Is this behavior a bug? This seems like useful filter to be able to omit the start or end date of the range.

**Comment by andris9** [comment]
It's not a bug but I can see how it can be confusing and probably should behave as you described, I'll try to change this

**Comment by radleta** [comment]
Thanks for the consideration. Appreciating you reviewing the issue.

**Comment by andris9** [comment]
Turned out fairly easy to change, so I updated the behavior right away with b626ea9c5e462dd34291cf8a8edc1d2bf473989e. You can leave range selectors empty which means that the beginning or end is open

**Comment by radleta** [comment]
Excellent! Thanks.
