### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by murtaza9000** [andris9/mailtrain#5]
Please check there are issues when I do npm start 

C:\wamp\www\automark\mailtrain>npm start

> mailtrain@1.0.0 start C:\wamp\www\automark\mailtrain
> node index.js

C:\wamp\www\automark\mailtrain\index.js:6
let config = require('config');
    ^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.10.35
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! mailtrain@1.0.0 start: `node index.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the mailtrain@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mailtrain package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mailtrain
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mailtrain
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\wamp\www\automark\mailtrain\npm-debug.log

**Comment by andris9** [comment]
Tou need at least node v5.0 like described in the requirements. Your node version is 0.10 which is not supported

**Comment by murtaza9000** [comment]
Thank you for quick reply, I did the version 5 but still same issue please help
root@automark:/var/www/mailtrain# NODE_ENV=production npm start

> mailtrain@1.0.0 start /var/www/mailtrain
> node index.js

â–€ â•¢â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–
/var/www/mailtrain/index.js:6
let config = require('config');
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
â–€ â•¢â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–

npm ERR! Linux 3.13.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! mailtrain@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mailtrain@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mailtrain package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mailtrain
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mailtrain
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/mailtrain/npm-debug.log

**Comment by murtaza9000** [comment]
it did work but now this error

`root@automark:/var/www/mailtrain# npm start

> mailtrain@1.0.0 start /var/www/mailtrain
> node index.js

â–€ â•¢â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–
WARNING: No configurations found in configuration directory:/var/www/mailtrain/config
WARNING: To disable this warning set SUPRESS_NO_CONFIG_WARNING in the environment.
/var/www/mailtrain/node_modules/mysql/lib/PoolConfig.js:10
  this.acquireTimeout     = (options.acquireTimeout === undefined)
                                    ^

TypeError: Cannot read property 'acquireTimeout' of undefined
    at new PoolConfig (/var/www/mailtrain/node_modules/mysql/lib/PoolConfig.js:10:37)
    at Object.createPool (/var/www/mailtrain/node_modules/mysql/index.js:24:28)
    at Object.<anonymous> (/var/www/mailtrain/lib/db.js:6:24)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/var/www/mailtrain/lib/models/users.js:6:10)`

**Comment by andris9** [comment]
There seems to be something wrong with the installation. I suggest you to re-download and re-install dependencies

1. Make sure you have the correct version of node

```
$ node -v
> v5.10.0
```

2. Download and install dependencies

```
git clone git://github.com/andris9/mailtrain.git
cd mailtrain
npm install
```

3. Create custom config file

```
cp config/default.toml config/development.toml
```

4. Edit MySQL config in `config/development.toml`

5. If you haven't imported the SQL table structure, the import it

```
mysql -u MYSQL_USER -p MYSQL_DB < setup/mailtrain.sql
```

6. Start the server

```
npm start
```
