### ISSUE TITLE
Subscription options

### ISSUE THREAD

**Issue by anselmh** [andris9/mailtrain#51]
One thing that other services do not provide at all currently and that I’d love to offer:

During sign-up process (or in profile edit mode), a subscriber can choose a few options to receive a newsletter (the following are only a few ideas):
* [Weekly] Short version
* [Weekly] Long version
* [Montly] Concatenated version
* Receive on Fridays
* Receive on Mondays

Hope you get the idea of what I’m trying to achieve here.
Do you have any idea if that’s already possible with mailtrain or if it would be possible to build that missing features for it without much effort?

Cheers,
— Anselm

**Comment by andris9** [comment]
The only option for now would be to add a new custom field Radio Button or Checkboxes and then add these options to this custom field (field type: "option for a group value"). When users sign up then they can select what they want ([example subscription form](https://mailtrain.org/subscription/SyTtB43f)). Here's how the custom field should look like:

![](https://cldup.com/XGJnYnl_-I.png)

Next create different segments that target each of these options and when creating campaigns then select segment as the recipient list. Here's how the segment should look like:

![](https://cldup.com/cE9kGp1Xmu.png)

**Comment by anselmh** [comment]
Thanks so much so far for documenting how I could do this today. Custom fields indeed sounds about right for that. :)
