### ISSUE TITLE
Segment Rule Issue: Any (rule match) appears to cause unsubscribes to be included in the count

### ISSUE THREAD

**Issue by radleta** [andris9/mailtrain#53]
We created a Segment with Rule Match set to Any. We then added a rule for Signup Date with a Date Range filter including both Start Date and End Date. The resulting total count exceed the total count for the list. 

We theorize the rule is somehow applying the Any to the unsubscribe exclusion rule which causes the unsubscribes to be included.

**Comment by andris9** [comment]
Yes, you are right, unsubscribed/bounced users are currently counted as well for segments. It's only the counter that is off, when sending out messages there is an extra check to only send to subscribed users. I'll fix the counter

**Comment by andris9** [comment]
Fixed with 3fa0e109af22d7c30d6d77645e9e113100606a45
