### ISSUE TITLE
Not sending emails - one reported as Opened (while never received)

### ISSUE THREAD

**Issue by OracleTuningGuy** [andris9/mailtrain#56]
Hi Mailtrain developers,

I have done a Digital Ocean install as per readme. 
One comment on Ubuntu install: 
  - /opt directory on default Ubuntu 14 droplet (Digital Ocean) did NOT exist, so I had to create it manually and then finalise install manually

Issue: so install now done. Created a list, a template and a campaign but it is not sending out emails.
I use localhost for sending out email and this works well on OS level.
Funny this is that it reports having sent one email (one email opened) to my own gmail account but its never received (not even in Spam).
Any idea where to start troubleshooting?

Kind regards,
Trond

**Comment by OracleTuningGuy** [comment]
Some additional testing done shows that nodemail works on its own and email received:

root@nsweb001:/opt/mailtrain# node testemail.js 
{ accepted: [ 'trondspain@gmail.com' ],
  rejected: [],
  pending: [],
  errors: [],
  envelope: { from: 'info@novoshore.com', to: [ 'trondspain@gmail.com' ] },
  messageId: '1464855551043-f911e683-8c4eaca6-508a8f66@novoshoere.com' }

The code used for this test:

'use strict';

var nodemailer = require('/opt/mailtrain/node_modules/nodemailer/lib/nodemailer');
var transporter = nodemailer.createTransport();

transporter.sendMail({
    from: 'info@novoshore.com',
    to: 'trondspain@gmail.com',
    subject: 'hello',
    text: 'hello world!'
}, function (err, response) {
    console.log(err || response);
});

**Comment by andris9** [comment]
For additional deguggin info you can check Mailtrain's log file which should reside in /var/log/mailtrain.log if you used the install script. Look for any error messages from the log.

To get even more details, turn on SMTP transaction logging by navigate to the Settings page in your Mailtrain installation and check the checkbox in Advanced settings: "Log SMTP transactions"

![](https://cldup.com/S5xDKGongT.png)

Now create a test campaign with some test addresses and try to send mail to it. After messages are sent check the log to see the actual SMTP log info. You should see if the message was actually delivered to your SMTP server or not.

**Comment by OracleTuningGuy** [comment]
Thanks Andris9

I see from the log you mentioned that there is an error:


ERR! VERP Error: listen EADDRINUSE :::25

ERR! VERP     at Object.exports._errnoException (util.js:953:11)

ERR! VERP     at exports._exceptionWithHostPort (util.js:976:20)

ERR! VERP     at Server._listen2 (net.js:1253:14)

ERR! VERP     at listen (net.js:1289:10)

ERR! VERP     at Server.listen (net.js:1385:5)

ERR! VERP     at SMTPServer.listen (/opt/mailtrain/node_modules/smtp-server/lib/smtp-server.js:101:24)

ERR! VERP     at module.exports.callback (/opt/mailtrain/services/verp-server.js:101:16)

ERR! VERP     at Immediate.testServer [as _onImmediate] (/opt/mailtrain/index.js:76:9)

ERR! VERP     at tryOnImmediate (timers.js:543:15)

ERR! VERP     at processImmediate [as _immediateCallback] (timers.js:523:5)


Address Already in use (port 25).

While looking at who is using port 25, I get:


tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1230/master


This is the postfix binaries and I assume this is the one that SHOULD be on port 25???????


What am I missing !


Kind regards,

Trond




From: Andris Reinman
Reply-To: andris9/mailtrain
Date: Thursday 2 June 2016 11:28
To: andris9/mailtrain
Cc: Trond Enstad, Author
Subject: Re: [andris9/mailtrain] Not sending emails - one reported as Opened (while never received) (#56)


For additional deguggin info you can check Mailtrain's log file which should reside in /var/log/mailtrain.log if you used the install script. Look for any error messages from the log.

To get even more details, turn on SMTP transaction logging by navigate to the Settings page in your Mailtrain installation and check the checkbox in Advanced settings: "Log SMTP transactions"

[https://camo.githubusercontent.com/819876fff022092a190725973658153351730fa6/68747470733a2f2f636c6475702e636f6d2f533578444b476f6e67542e706e67]<https://camo.githubusercontent.com/819876fff022092a190725973658153351730fa6/68747470733a2f2f636c6475702e636f6d2f533578444b476f6e67542e706e67>

Now create a test campaign with some test addresses and try to send mail to it. After messages are sent check the log to see the actual SMTP log info. You should see if the message was actually delivered to your SMTP server or not.

**Comment by andris9** [comment]
Setting up VERP based bounce handling is kind of tricky. In this case you should not run your mailtrain installation in the same machine as your postfix (assuming you send messages through postfix), additionally the mailtrain installation should have a dedicated MX hostname for something like "bounces.yourdomain.com" and accessible from the internet.

The message flow in this case is like this:

mailtrain -> Nodemailer (SMTP from address: identifier@bounces.yourdomain.com, from header: sender@yourdomain.com) -> Postfix -> Recipient.

If message bounces, then the bounce is not sent to sender@yourdomain.com but identifier@bounces.yourdomain.com and bounces.yourdomain.com should resolve into your Mailtrain installation server where the VERP handler is listening on port 25.

This should not prevent sending though. Check the SMTP transactions and your postfix logs, it might be that Postfix blocks messages with VERP SMTP envelope. You can try to turn off VERP support and see if there is any change

**Comment by OracleTuningGuy** [comment]
Hi Andris

I do NOT have VERP configured:

[cid:3C734D11-0890-4ABC-BA36-1F8F4CE35E9A]




Kind regards,
Trond


From: Andris Reinman
Reply-To: andris9/mailtrain
Date: Thursday 2 June 2016 12:12
To: andris9/mailtrain
Cc: Trond Enstad, Author
Subject: Re: [andris9/mailtrain] Not sending emails - one reported as Opened (while never received) (#56)


Setting up VERP based bounce handling is kind of tricky. In this case you should not run your mailtrain installation in the same machine as your postfix (assuming you send messages through postfix), additionally the mailtrain installation should have a dedicated MX hostname for something like "bounces.yourdomain.com" and accessible from the internet.

The message flow in this case is like this:

mailtrain -> Nodemailer (SMTP from address: identifier@bounces.yourdomain.com<mailto:identifier@bounces.yourdomain.com>, from header: sender@yourdomain.com<mailto:sender@yourdomain.com>) -> Postfix -> Recipient.

If message bounces, then the bounce is not sent to sender@yourdomain.com<mailto:sender@yourdomain.com> but identifier@bounces.yourdomain.com<mailto:identifier@bounces.yourdomain.com> and bounces.yourdomain.com should resolve into your Mailtrain installation server where the VERP handler is listening on port 25.

This should not prevent sending though. Check the SMTP transactions and your postfix logs, it might be that Postfix blocks messages with VERP SMTP envelope. You can try to turn off VERP support and see if there is any change

**Comment by OracleTuningGuy** [comment]
I aslo see from /var/log/mail.log:


root@nsweb001:/var/log# tail -f mail.log

Jun  1 06:53:52 nsweb001 postfix/smtpd[2257]: connect from localhost[127.0.0.1]

Jun  1 06:53:52 nsweb001 postfix/smtpd[2257]: disconnect from localhost[127.0.0.1]

Jun  1 08:09:57 nsweb001 postfix/master[1214]: daemon started -- version 2.11.0, configuration /etc/postfix

Jun  1 08:49:25 nsweb001 postfix/smtpd[1816]: connect from localhost[127.0.0.1]

Jun  1 08:49:25 nsweb001 postfix/smtpd[1816]: disconnect from localhost[127.0.0.1]

Jun  2 04:49:11 nsweb001 postfix/master[1230]: daemon started -- version 2.11.0, configuration /etc/postfix

Jun  2 05:21:36 nsweb001 postfix/smtpd[1684]: connect from localhost[127.0.0.1]

Jun  2 05:21:36 nsweb001 postfix/smtpd[1684]: disconnect from localhost[127.0.0.1]

Jun  2 05:56:19 nsweb001 postfix/smtpd[1949]: connect from localhost[127.0.0.1]

Jun  2 05:56:19 nsweb001 postfix/smtpd[1949]: disconnect from localhost[127.0.0.1]

^C



Also note that MailTrain reports SMPT settings as correct:

[cid:3D77A470-4A81-4A5B-98E6-DFBF89C3A4ED]

Kind regards,
Trond

From: Andris Reinman
Reply-To: andris9/mailtrain
Date: Thursday 2 June 2016 12:12
To: andris9/mailtrain
Cc: Trond Enstad, Author
Subject: Re: [andris9/mailtrain] Not sending emails - one reported as Opened (while never received) (#56)


Setting up VERP based bounce handling is kind of tricky. In this case you should not run your mailtrain installation in the same machine as your postfix (assuming you send messages through postfix), additionally the mailtrain installation should have a dedicated MX hostname for something like "bounces.yourdomain.com" and accessible from the internet.

The message flow in this case is like this:

mailtrain -> Nodemailer (SMTP from address: identifier@bounces.yourdomain.com<mailto:identifier@bounces.yourdomain.com>, from header: sender@yourdomain.com<mailto:sender@yourdomain.com>) -> Postfix -> Recipient.

If message bounces, then the bounce is not sent to sender@yourdomain.com<mailto:sender@yourdomain.com> but identifier@bounces.yourdomain.com<mailto:identifier@bounces.yourdomain.com> and bounces.yourdomain.com should resolve into your Mailtrain installation server where the VERP handler is listening on port 25.

This should not prevent sending though. Check the SMTP transactions and your postfix logs, it might be that Postfix blocks messages with VERP SMTP envelope. You can try to turn off VERP support and see if there is any change

**Comment by andris9** [comment]
If you get VERP errors then you probably have configuration file set up like this:

```toml
[verp]
enabled=true
```

Otherwise the VERP server is not started.

You should enable SMTP transactions logging for Mailtrain and check the logs that start with "info Mail"

```
cat /var/log/mailtrain.log | grep "info Mail"
```

**Comment by OracleTuningGuy** [comment]
Thanks a lot Andris

Nothing in the log.
BUT indeed – the verp was enabled in production.toml file.
I set it to false and restarted.
Immediately I got emails coming in.

Thanks a million !

Kind regards,
Trond


From: Andris Reinman
Reply-To: andris9/mailtrain
Date: Thursday 2 June 2016 12:46
To: andris9/mailtrain
Cc: Trond Enstad, Author
Subject: Re: [andris9/mailtrain] Not sending emails - one reported as Opened (while never received) (#56)


If you get VERP errors then you probably have configuration file set up like this:

[verp]
enabled=true

Otherwise the VERP server is not started.

You should enable SMTP transactions logging for Mailtrain and check the logs that start with "info Mail"

cat /var/log/mailtrain.log | grep "info Mail"

**Comment by andris9** [comment]
Great!
