### ISSUE TITLE
Segment Rule Issue: Any (rule match) does not appear to work

### ISSUE THREAD

**Issue by radleta** [andris9/mailtrain#58]
We have created a segment with the below criteria.

Rule Match: Any
Rule: Signup Date, Start: 240 days before today
Rule: Latest Open, Start: 240 days before today

The count that shows for the segment is all records for the list instead of the ones that match the above criteria. I've double checked MySql data using the below query to ensure data exists properly and both queries resulted in the correct count.

```SQL
SELECT COUNT(*)
FROM mailtrain.subscription__1
WHERE status = 1
	AND (
		(created > DATE_ADD(NOW(), INTERVAL -240 DAY))
		OR (latest_open > DATE_ADD(NOW(), INTERVAL -240 DAY))
        );

SELECT COUNT(*)
FROM mailtrain.subscription__1
WHERE status = 1
	AND (
		(status_change > DATE_ADD(NOW(), INTERVAL -240 DAY))
		OR (latest_open > DATE_ADD(NOW(), INTERVAL -240 DAY))
        );
```

There appears to still be a logic bug with the Rule Match 'Any' option. In fact, even when removing the rules and just having one rule the count still shows the entire subscribed list count.

**Comment by andris9** [comment]
Could you check if the latest master fixes your issue? There was a bug with resolving ranges in ANY queries.
