### ISSUE TITLE
Amazon SES sending limit / sec

### ISSUE THREAD

**Issue by shamank** [andris9/mailtrain#62]
Hi! I've successfully configured it to use through Amazon SES. The only thing I'm a bit worried about is the sending limit per second. In my case, Amazon allowed me to send 14 emails/sec, so I don't know how can I limit the mailer to achieve this. For now, I changed the SMTP setting of 5 to 1 max connection, but it doesn't imply the amount to send per second, right? Thank you for such a great new project!

**Comment by andris9** [comment]
It should probably work even with the sending limit. If Mailtrain hits the sending limit, it backs off for 1 sec. which should remove the limits, so it can resend the failed message. Maybe in the future I come up with an actual rate limiting solution but for now it should be good enough. Sending might be slower than supposed to if you hit the limit often but it should work in general.

**Comment by shamank** [comment]
Ok. I'll let you know about the sending performance once we launch a large campaign. I didn't take a look at the sending part yet so I'll ask you. How can I monitor the frecuency of that 1 sec rule you mention? I mean, does it appear in the log file or is there something I might watch to know how many times the process had to apply this or the amount of failed emails because of this? Thanks.
