### ISSUE TITLE
Warning in errorlog

### ISSUE THREAD

**Issue by shamank** [andris9/mailtrain#64]
This is appearing in the errorlog every time I start the service. I'm not sure what are the consequences of this...
```
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
```
I'm not using cache for now. Should I?

**Comment by andris9** [comment]
It means you are not using Redis to store session data but the default built-in in memory store. You can safely ignore this warning
