### ISSUE TITLE
Getting email ID

### ISSUE THREAD

**Issue by shamank** [andris9/mailtrain#65]
Hi. Is it possible to get the internal email ID (in the MySQL table) just to get a unique numeric field referencing the email in the template? Ie. with a tag like [ID]
This is useful for Google Analytics to track some stuff. Thanks.

**Comment by andris9** [comment]
v1.12.0 includes new merge tags SUBSCRIPTION_ID, LIST_ID and CAMPAIGN_ID. These aren't numeric though but unique string ID's
