### ISSUE TITLE
Email template image not redirecting to the link

### ISSUE THREAD

**Issue by sau1994** [andris9/mailtrain#67]
We have given the service address url of our local host in the general setting. And created a template and coded it in HTML which we send this template to various email ids using spark post smtp settings. we wanted that when user clicks on the template image the user gets redirected to the new url which was assigned to the template which was designed in HTML.

This happens, email gets sent and template shows up but when the user clicks on the image it is not redirected to the given url. While emails sent to our internal ip addresses redirects to the link properly. The issue comes up when user access the email from the network different from our organization it shows the url of the our local host machine which is provided in the service address earlier.

**Comment by andris9** [comment]
Are you trying to use localhost/intranet URL's in a message? How would you expect Mailtrain to help in this case as local URL's are never accessible to anyone outside your own network?

**Comment by sau1994** [comment]
Yes. As it is hosted on our local machine. It would be great if you can please tell us what changes can we make in our settings so that any user outside our network if clicks on the templates should be redirected to the URL mentioned in the HTML code.

**Comment by andris9** [comment]
Check that Mailtrain is accessible from outside your network (check that the service url option listed in the Settings page is a valid url that points to your Mailtrain installation). Only use absolute urls in the message template
