### ISSUE TITLE
Create an API method for user removal from list.

### ISSUE THREAD

**Issue by MaheshCasiraghi** [andris9/mailtrain#68]
Right now the API allows to add a user to a list, to subscribe, and unsubscribe them. We were not able to find an exposed API Method that allows for removal of such user. Does this method exist and it is undocumented, or it does not exist? Thank you.

**Comment by andris9** [comment]
This method does not exist yet, I'll add it to the API.

**Comment by MaheshCasiraghi** [comment]
Thank you @andris9, looking forward to it! :-)

**Comment by andris9** [comment]
Deleting a subscriber is available from v1.13.0

**Comment by rikmendes** [comment]
How can it be used ? I have users that unsubscribed themselves and are still getting emails, how is that even possible ? do I have to manually blacklist them ? Why are they getting email if already unsubscribed from themselves ?
