### ISSUE TITLE
install.sh installation is not accessible after installation is finished on digitalocean

### ISSUE THREAD

**Issue by icemaker** [andris9/mailtrain#69]

**Comment by icemaker** [comment]
I made automatic installed on ubuntu 14.04 on digitalocean as suggested, but the server is inaccessible

**Comment by andris9** [comment]
Usually this means that the installation process was killed due to hitting memory limits. Try to use a larger droplet size to overcome this or run the install script seversl times until it succeeds if you are installimg through ssh. Mailtrain itself should run on the 512MB droplet as well but the installation might require a bit more.

**Comment by andris9** [comment]
Actually it seems there was a bug in database setup in v1.12.0 that was probably the reason why Mailtrain installation failed. This is fixed in v1.13.0

**Comment by icemaker** [comment]
i tried the automatic installation again using this:
curl https://raw.githubusercontent.com/andris9/mailtrain/master/setup/install.sh | sudo bash

Droplet 4GB Ram

i cant access the droplet:
Network Error (tcp_error) 

A communication error occurred: "Connection reset by peer"
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.

For assistance, contact your network support team.

**Comment by andris9** [comment]
Is there a /var/log/mailtrain.log file in the droplet?

**Comment by icemaker** [comment]
No such file available

**Comment by andris9** [comment]
If you run the install script in Digital Ocean does the console log show any errors? Does it show you the ending "Success!" message or does the install script end with some other message?

**Comment by icemaker** [comment]
seems mysql problem look at below:

Reading package lists... Done 

## Run `apt-get install nodejs` (as root) to install Node.js v6.x and npm

Reading package lists...
Building dependency tree...
Reading state information...
pwgen is already the newest version.
ufw is already the newest version.
git is already the newest version.
mysql-server is already the newest version.
nodejs is already the newest version.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 mysql-server : Depends: mysql-server-5.5 but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

**Comment by icemaker** [comment]
Where you able to rectify the problem?
