### ISSUE TITLE
SMTP settings

### ISSUE THREAD

**Issue by preexo** [andris9/mailtrain#7]
I am having trouble getting a connection to my SMTP server. I always get the message "Connection refused, check hostname and port.".
I am suspecting that it has to do with the SSL verification. Is there a chance to disable the SSL verification? I would be willing to contribute, but just started to check out the project and probably need some direction first.

Those settings work for me using heirloom-mailx for example:
```
echo "hello world" | /usr/bin/heirloom-mailx -v -r "mail@domain.com" -s "subject" -S smtp="host:port" -S smtp-use-starttls -S smtp-auth=login -S smtp-auth-user="smpt-user@domain.com" -S smtp-auth-password="smtp-password" -S ssl-verify=ignore "mail@domain.com"
```
The only difference I can spot is the `ssl-verify=ignore` so far.

**Comment by andris9** [comment]
Yes, you're right. Currently Mailtrain uses strict SSL verification. I'll add a config option to disable this

**Comment by jasonstrimpel** [comment]
Also having this issue. Entering correct details as confirmed through email admin and unable to connect. Can't provide any specifics other than I'm able to connect to the SMTP server through command line.

**Comment by andris9** [comment]
There is a new option "Allow self-signed certificates" in advanced smtp settings that makes it possible to ignore certificate errors
