### ISSUE TITLE
Sending limits

### ISSUE THREAD

**Issue by preexo** [andris9/mailtrain#73]
We have a mail provider which has a limit of 55 mails per minute, how can we ensure that mailtrain does not send out more emails per minute? Is there a throttle feature?

**Comment by andris9** [comment]
Currently there is no throttling support. What you can do is to limit the Max Connections to 1 and Max Messages to some very low number like 1 to artificially keep the sending speed slow.

**Comment by preexo** [comment]
@andris9 - thanks for the suggestion. From your experience, where does that put us by messages/second when max connection set to 1 and maximum messages set to 1 as well? Thanks!

**Comment by andris9** [comment]
Depends on your connection speed. 55 messages/minute is really low number, less than a message in second. You should probably just try it out what happens. If you hit the rate limiter then Mailtrain retries the same message up to 5 times in a 15 sec window.

**Comment by andris9** [comment]
The latest commit in master branch has support for throttling. Open Settings page and set 3300 messages/hour as the Throttling limit (its the same as 55 messages/minute).
