### ISSUE TITLE
subject line is missing from the RSS create and edit views

### ISSUE THREAD

**Issue by necenzurat** [andris9/mailtrain#76]
Just installed mailtrain, set it up and saw that the email subject is missing from both of the views.
Any ideas?

**Comment by andris9** [comment]
In case of RSS campaigns the subject line comes from the RSS file. A separate message is sent for every new post in the RSS, the posts are not aggregated into one before sending.

**Comment by necenzurat** [comment]
It would be really nice to send an aggregate of the posts since last day, with custom subject support and custom templates (foreach loops). Basically to copy Mailchimp's fuctionallity. 
Any plans for implementing?
