### ISSUE TITLE
HTML are empty ?

### ISSUE THREAD

**Issue by cnicodeme** [andris9/mailtrain#77]
Hi,

I used MailTrain to send an email to my contacts using the HTML and plain text messages from the template, but oddly, some of my contacts reported me that their email was empty.

I checked with them and indeed, there is no body in the email.

Is this something I am the only one to experience ? I tried to find in the issues about this problem but couldn't find anything.

I can share more details if you ask me what to give :)

**Comment by andris9** [comment]
Interesting, I haven't heard this one yet. It would help a lot if you could somehow get the raw email sources, one for a successful delivery and one for the empty one, so I could compare these.

In gmail you get the raw source when selecting "Show original" from the message menu. In desktop clients there is usually "Save as eml" or something like that. Anyway, its the plaintext format where you can see the full message headers and also the actual body of the message.

**Comment by cnicodeme** [comment]
Hi,

yes indeed, here's the pastebin of the correct email received : 
http://pastebin.com/9SrZLHbC

And the pastebin of an empty email (note that it's a reply from one of my contact, so maybe the reply removed some informations) : 
http://pastebin.com/vr86HpYd

**Comment by andris9** [comment]
Thanks. Unfortunatelly forwarding the message removes all required information. I can see from the headers that the recipient is using Outlook 14. Could he/she store the message in msg format (File->Save As) and send it as an attachment or pasting it to pastebin?

**Comment by cnicodeme** [comment]
Hi, sorry for the late reply.

I asked one of my contact to send me the `.eml` file. I renamed it to `.txt` because Github disallow `.eml` files, and I removed his email to a generic one to avoid his email to be public, but other than that, this is the complete email he received :)

Let me know if that helps !

[noname.txt](https://github.com/andris9/mailtrain/files/378099/noname.txt)

**Comment by andris9** [comment]
I don't see anything wrong with that email. This is how it is rendered in my mail client: https://cloudup.com/c5T3VnAtQsb

I think that the issue is related to the combination of Outlook 2010 that the recipient is using and SparkPost that modifies the message. Maybe try to use a different provider that does not alter the message structure so much and see if there is a difference? For now it seems that Mailtrain delivers the messages is supposed to but it breaks in the client.

**Comment by cnicodeme** [comment]
Thank you for the feedback. I'll try with Mailgun, and see if there is any changes next time I send an email.

Good luck with Mailtrain, it's a great product!
