### ISSUE TITLE
Setting up SMTP Server / UX issue

### ISSUE THREAD

**Issue by nicostuhlfauth** [andris9/mailtrain#78]
Missing data binding, when submitting button "Check SMTP Config"

**Step by step:**
1. Opening settings
2. Editing fields of SMTP config
3. Clicking Check SMTP Config

**Actual Behaviour:**
System checks configuration saved in database; to check new configuration, user needs to scroll down and manually update first.

**Expected Behaviour:**
Clicking "Check SMTP Config" checks the NEW configuration / missing data binding

**Comment by andris9** [comment]
Fixed in v1.15.0. Form data is sent to server via AJAX and the data from the form is used to validate SMTP settings.
