### ISSUE TITLE
Template name not set cause bad gateway error

### ISSUE THREAD

**Issue by guilro** [andris9/mailtrain#79]
In the template creation form, not filling the template name field causes a 502 Bad Gateway Error when using nginx in reverse proxy.

The error "Template name not filled." appears as flash message only if you load other page such as the main page.

**Comment by andris9** [comment]
I can't reproduce this. Does this happen with the default values? Eg. you open the "Create template" page and then hit the submit button without changing anything or does it require some special templating code as well?

**Comment by guilro** [comment]
Can't reproduce it myself neither :/
