### ISSUE TITLE
Correct DNS records for VERP

### ISSUE THREAD

**Issue by alikuru** [andris9/mailtrain#81]
Hi,

After I've seen iRedMail on the Mailtrain homepage, I decided to give it a chance and set up my own mail server. As far as I understand from the setup, since this is a standalone mail server and there are no webhook functionality similar to that of Sparkpost's or Mailgun's for tracking message events, VERP seems to be only option.

On the settings section of the Mailtrain it states that;
>To get VERP working you need to set up a DNS MX record that points to your Mailtrain hostname. [...] This way if anyone tries to send email to someuser@bounces.my.domain.com then the email should end up to this server.

So I set an MX for the "bounces.my.domain.com" pointing "my.domain.com", where my Mailtrain setup resides:

    bounces.my.domain.com. 300     IN      MX      10 my.domain.com.

Activated VERP through Mailtrain config & panel for bounces.my.domain.com and for testing, created a list with these test accounts:

    bounce-test@service.socketlabs.com
    bounce@simulator.amazonses.com
    hard_bounce@test.mandrillapp.com
    soft_bounce@test.mandrillapp.com
    bounceme@my.domain.com

When I hit send, Mailtrain shows me that all 5 are bouncing. However, when I try to check the bounced emails list from campaign report page, it says `"No data available in table"`.

Any ideas on what am I doing wrong?

**Comment by alikuru** [comment]
It appears that the issue is related to iRedMail's SMTP SASL AUTH policies.

I guess envelope changes created by activating VERP confuses server, hence it rejects all mail from the sender. Appliying the workaround [described here] (http://www.iredmail.org/forum/topic11192-iredmail-support-smtp-error.html) fixed the issue.

**Comment by andris9** [comment]
That's a good catch, I'll add this note to the docs
