### ISSUE TITLE
List-ID header gets mangled

### ISSUE THREAD

**Issue by rchavik** [andris9/mailtrain#82]
I'm finding that the List-ID header gets mangled, causing gmail to show weird names as per screenshot. In that test, the List name is: "My Subscribers".

![headers](https://cloud.githubusercontent.com/assets/39490/17553020/a462ca8c-5f2d-11e6-97b9-ca59811d3341.png)

Traced it to https://github.com/andris9/mailtrain/blob/master/services/sender.js#L310, but I'm not clear on what the regex is trying to accomplish, or why it needs it at all.

Can you clarify.

**Comment by andris9** [comment]
Fixed by fb7fd7238f3bee80923f3d586b928274ae858fe5, update your code to the latest commit in the master branch
