### ISSUE TITLE
How to delete a campaign that is no longer associated with a list?

### ISSUE THREAD

**Issue by alikuru** [andris9/mailtrain#84]
I created a list for testing purposes and started to send a campaign. After I've finished the test, I deleted the list and tried to do the same for the associated campaign. Mailtrain denied my request of editing the campaign with a `Selected list not found` warning message.

Is there any way to edit/delete a campaign after the list it has been sent to no longer exists?

**Comment by andris9** [comment]
Fixed by fb7fd7238f3bee80923f3d586b928274ae858fe5, update your code with the latest version in the master branch.
