### ISSUE TITLE
Unexpected restart with VERP

### ISSUE THREAD

**Issue by alikuru** [andris9/mailtrain#87]
I noticed sudden logouts from Mailtrain during a campaign and inspected application logs for detail. As far as I can tell, some bounces coming through VERP triggers an error and forces Mailtrain to restart, which terminates season and ask user to login again.
    
Here is a sample from the logs, hope it helps:
    
    Mailtrain-0 verb VERP Incoming message for Campaign 20, List 6, Subscription 31033
    Mailtrain-0 TypeError: Cannot read property 'match' of undefined
    Mailtrain-0     at BounceHandler.format_status_code (/var/www/my.domain.com/http/node_modules/bounce-handler/lib/bouncehandler.js:658:27)
    Mailtrain-0     at BounceHandler.get_action_from_status_code (/var/www/my.domain.com/http/node_modules/bounce-handler/lib/bouncehandler.js:682:24)
    Mailtrain-0     at BounceHandler.parse_machine_parsable_body_part (/var/www/my.domain.com/http/node_modules/bounce-handler/lib/bouncehandler.js:573:30)
    Mailtrain-0     at BounceHandler.get_the_facts (/var/www/my.domain.com/http/node_modules/bounce-handler/lib/bouncehandler.js:214:33)
    Mailtrain-0     at BounceHandler.parse_email (/var/www/my.domain.com/http/node_modules/bounce-handler/lib/bouncehandler.js:96:21)
    Mailtrain-0     at PassThrough.<anonymous> (/var/www/my.domain.com/http/services/verp-server.js:77:45)
    Mailtrain-0     at emitNone (events.js:72:20)
    Mailtrain-0     at PassThrough.emit (events.js:166:7)
    Mailtrain-0     at endReadableNT (_stream_readable.js:921:12)
    Mailtrain-0     at nextTickCallbackWith2Args (node.js:442:9)
    Mailtrain-0 WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
    Mailtrain-0 WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
    Mailtrain-0 Warning: connect.session() MemoryStore is not
    Mailtrain-0 designed for a production environment, as it will leak
    Mailtrain-0 memory, and will not scale past a single process.
    Mailtrain-0 info
    Mailtrain-0  sql Database check completed
    Mailtrain-0 info Express WWW server listening on port 2996
    Mailtrain-0 info
    Mailtrain-0 VERP Server listening on port 25
    Mailtrain-0 verb UTC Updating timezone offsets
    Mailtrain-0 info Service
    Mailtrain-0  All services started

**Comment by andris9** [comment]
Seems to be a bug in the bouncehandler dependency. I'll see what I can do about it.

**Comment by andris9** [comment]
I added an extra check to catch such bounce parsing errors, so the app should not die anymore if it can't handle a verp message. https://github.com/andris9/mailtrain/commit/175b8eb94dd056b5d0556179371cdaa39e74243e#diff-4c3e58cdc8f554e2f17d56d2507a1745R79
