### ISSUE TITLE
drip campains

### ISSUE THREAD

**Issue by JensC** [andris9/mailtrain#9]
Would be a wondelful addition to this great software :-).
Installing was a breeze BTW.

**Comment by andris9** [comment]
I'm not sure about full core automation support, at least for now but I guess it would be possible to emulate dripping by upgrading segmentation rules to allow using relative time ranges in addition to fixed ranges – eg. use a rule like "3 days after signup". I'll try to come up with a solution for this

**Comment by andris9** [comment]
Implemented in v1.12.0
