### ISSUE TITLE
How to use it with Mailgun?

### ISSUE THREAD

**Issue by Nowaker** [andris9/mailtrain#91]
[Bounce Handling section in README.md](https://github.com/andris9/mailtrain#bounce-handling) suggests Mailgun is supported. But how do I make Mailtrain send emails via Mailgun?

**Comment by andris9** [comment]
See the Wiki entry [here](https://github.com/andris9/mailtrain/wiki/Setting-up-Webhooks-for-Mailgun)

**Comment by Nowaker** [comment]
This is not the answer... This is bounce handling with Mailgun - but how do I **send** with Mailgun?

**Comment by andris9** [comment]
Oh, sorry, misread it. You need to create SMTP credentials through the Mailgun web page and use this with the following settings:

  * host: smtp.mailgun.org
  * port: 465
  * encryption: Use TLS (with port 465)
  * username: the email address you generated the credentials for
  * password: the password for the generated user

**Comment by andris9** [comment]
once you have filled out all the SMTP details in the Mailtrain Settings page (right top corner, click on the username and select Settings), you can verify the credentials by clicking on the "Check SMTP config" button

**Comment by andris9** [comment]
![screen shot 2016-09-13 at 9 43 10](https://cloud.githubusercontent.com/assets/132242/18463957/82e561b6-7996-11e6-8397-1a05a0a6bb2c.png)

**Comment by Nowaker** [comment]
Oh! Thanks. I got used to APIs so much that I totally forgot legacy SMTP stuff still exists at Mailgun.

Would API integration, if ever implemented, speed up email push times?

**Comment by andris9** [comment]
Providers only label SMTP as legacy because they can lock you in this way, in the end it is still RFC822 messages over SMTP. Using API can speed up some use cases but not all, for example sending different messages through pooled SMTP is faster than dropping these messages over HTTP because of less overhead. If you let the provider to handle all rendering by providing a template and a list of recipients then yes, this would be faster. Besides you would need a separate API integration for every mail provider since these usually differ quite a lot but all of them support SMTP.

**Comment by Nowaker** [comment]
Nobody locks me in as I use a Mailgun Rails gem which I can replace with SendGrid's in a matter of seconds. :)

Isn't SMTP a way chattier protocol protocol than HTTP? If we have pooled HTTP and pooled SMTP, then the former should perform better, or am I missing something? My apps send emails in background using [Sidekiq](http://sidekiq.org/).

**Comment by Nowaker** [comment]
(Nothing in what I said should be considered as a feature request or a gripe. Just being curious how SMTP can perform better than HTTP.)

**Comment by andris9** [comment]
It really depends on the context I guess. There are different kind of API's out there and these allow you to do different kind of things. The simplest ones allow you to provide a predefined set of parameters like `from` and `to` and `text` and `html` and maybe some kind of list of attachments. If you only want to send a message where you want to define `to` and `text` and you send it over HTTP as www-form-urlencoded, then SMTP could probably not be able to beat that. On the other hand if you want to use complex message structures, for example you want to encrypt messages with pgp-mime or even set which attachment goes into which mime node in the final message (this defines how the email client should render the attachment) then such API most probably does not allow it and you would have to generate the raw rfc822 message yourself. Once you are sending complex JSON data structures or raw rfc822 messages in batches then SMTP is most probably more effective.

SMTP gets less chattier if you reuse the same connection to send several messages. You do have the initial handshake: the server lists the extensions it supports and you authenticate yourself etc. but once you are already sending messages with that connection then you only need to provide a minimal amount of data for every new message as long as you do not close the connection

```
C: MAIL FROM:<sender@address>\r\n (14 bytes overhead)
C: RCPT TO:<recipient@address>\r\n (12 bytes overhead)
S: 250 OK\r\n (8 bytes overhead)
S: 250 OK\r\n (8 bytes overhead)
C: DATA\r\n (6 bytes overhead)
S: 354 OK\r\n (8 bytes overhead)
C: <rfc822 message content>
```
 In this example you would have 32 bytes overhead from client to server and 24 bytes overhead in server responses. Thats 56 bytes in total that is not part of the message but related to the protocol. In comparison with HTTP even the initial POST header + Host: header + credentials might take more and you're not providing anything about the message yet

```
POST /v3/example.com/messages HTTP/1.1\r\n
Host: api.mailgun.net\r\n
Authorization: Basic YXBpOmtleS0wLTExMTExMTExMTExMS0tMjIyMjIyMjIyMjIyMjIyMg==\r\n
```

(the key uses the same amount of bytes than my actual Mailgun API key)

At this point you're already at 142 bytes and you have delivered zero bytes of data related to the actual message. And you need to do this for every message even if you use `Connection: Keep-Alive` header while in SMTP once you're authenticated you do not need to do this again while the connection is alive.

API's usually shine and are really superior in cases where you provide a single message template with a list of recipient related data. There is no way SMTP can ever match this.

**Comment by Nowaker** [comment]
I think what really matters isn't the byte overhead but the latency, doesn't it? AFAIR, SMTP waits for an okay to RCPT TO before sending data. I'd be interesting to see an actual benchmark.

**Comment by andris9** [comment]
If the server supports pipelining (and most of the servers do) then you only have to wait the response for a single command, DATA, before you can continue.

Nevertheless, every mail sending provider has a different and not fully compatible API, so once you start using something specific for a single provider then you can't really switch anymore. The "multi-lingual" API wrappers usually level out the service specific options, so you loose the advanced features that you actually might be interested in or if you're not using one of the big providers (there are literally thousands (if not more) of providers around the world like SendGrid or Mailgun) then the multi-lingual wrapper most probably does not know that specific API (or there isn't even any API available) and you still need to use the vendor provided library (which yet again means lock-in).

Being tied to a single vendor might be OK for a lot of cases but for a general use software like Mailtrain, that must be able to support every provider out there, it is not really an option. The current SMTP based sending is already fast enough, so using an API would not make anything much faster even if there would be a difference in favor of an API.

**Comment by yashsaxena** [comment]
Andris, if someone was to try create vendor specific extensions to be able to use HTTP APIs, how easy or difficult would it be, if possible?
