### ISSUE TITLE
SMTP error 442 with Mailtrain/ZoneMTA on sending emails

### ISSUE THREAD

**Issue by flocu** [andris9/mailtrain#96]
Tried to send an email to a list of 4 subscribers. Getting a 442 SMTP error for every mail.

In Mailtrain - Settings SMTP Settings seem to work:
"SMTP settings verified, ready to send some mail!"

Mailtrain was installed with install.sh on Ubuntu 16.04 64 Bit
Mailtrain is running
Zone-MTA is running and listening on 587

Any idea what this could be?

This is from syslog. Unfortunately there is no mailtrain.log or zone-mta.log to be found, even with logging enabled in conf file and settings.

```
Sep 26 03:10:01 pceoupc node[7623]: ERR! Mail Pool Error for #63: Mail command failed: 442 Invalid status code 404
Sep 26 03:10:01 pceoupc node[7623]: ERR! Mail Send Error: Mail command failed: 442 Invalid status code 404
Sep 26 03:10:01 pceoupc node[7623]: ERR! Mail Error: Mail command failed: 442 Invalid status code 404
Sep 26 03:10:01 pceoupc node[7623]: ERR! Mail     at SMTPConnection._formatError (/opt/mailtrain/node_modules/smtp-connection/lib/smtp-connection.js:528:15)
Sep 26 03:10:01 pceoupc node[7623]: ERR! Mail     at SMTPConnection._actionMAIL (/opt/mailtrain/node_modules/smtp-connection/lib/smtp-connection.js:1252:30)
Sep 26 03:10:01 pceoupc node[7623]: ERR! Mail     at SMTPConnection.<anonymous> (/opt/mailtrain/node_modules/smtp-connection/lib/smtp-connection.js:759:14)
Sep 26 03:10:01 pceoupc node[7623]: ERR! Mail     at SMTPConnection._processResponse (/opt/mailtrain/node_modules/smtp-connection/lib/smtp-connection.js:669:16)
Sep 26 03:10:01 pceoupc node[7623]: ERR! Mail     at SMTPConnection._onData (/opt/mailtrain/node_modules/smtp-connection/lib/smtp-connection.js:493:10)
Sep 26 03:10:01 pceoupc node[7623]: ERR! Mail     at emitOne (events.js:96:13)
Sep 26 03:10:01 pceoupc node[7623]: ERR! Mail     at Socket.emit (events.js:188:7)
Sep 26 03:10:01 pceoupc node[7623]: ERR! Mail     at readableAddChunk (_stream_readable.js:176:18)
Sep 26 03:10:01 pceoupc node[7623]: ERR! Mail     at Socket.Readable.push (_stream_readable.js:134:10)
Sep 26 03:10:01 pceoupc node[7623]: ERR! Mail     at TCP.onread (net.js:543:20)
```

**Comment by andris9** [comment]
This happens when ZoneMTA tries to fetch information about the sender from mailtrain and the check fails. Depending on the version of ZoneMTA you have the URL that is used can be either `"getSenderConfig"` or `"plugins.core/http-config.url"`. This is mostly needed for fetching DKIM signing key and if you do not need it, then you can check that value to `false`

**Comment by flocu** [comment]
Thanks, that helped. I'm running mailtrain on port 3000, so I had to change the zone-mta config to reflect that. 

sending emails works now
DKIM works
