### ISSUE TITLE
Segment a long list in chunks

### ISSUE THREAD

**Issue by JensC** [andris9/mailtrain#98]
Is there a way to segment a long list in say chunks of 300 with a custom field?  Thanks.

**Comment by andris9** [comment]
I don't think there is a sane way for this. One solution would be to create a custom number field and assign every subscriber an ordered sequence number. Then you could use this custom field for creating the segment (eg. "the number field must be from 1 to 300" or "number field must be from 301 to 600")

**Comment by JensC** [comment]
Thanks for you answer. I used some sql to setup a custom number field and did like you suggested. However I think this would be a nice extension to have. I think mailchimp has this feature. Great app btw, think I will use ir more often now.
